- name: ensure subnets exists
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ eks_vpc_results.vpc.id }}"
    az: "{{ eks_region}}{{ item.zone }}"
    cidr: "{{ item.cidr }}"
    tags:
      Name: "eks-subnet-{{ item.zone }}"
      KubernetesCluster: "{{ eks_cluster_name }}"
    purge_tags: no
    region: "{{ eks_region }}"
  register: eks_subnet_results
  loop: "{{ eks_subnets }}"
  ignore_errors: yes
