eks_vpc_name: aws-eks-vpc
eks_region: ap-south-1
eks_vpc_cidr: 10.0.0.0/16
eks_cluster_name: kube2019rishabh
eks_kubeconfig_env: []

eks_subnets:
  - cidr: 10.0.1.0/24
    zone: a
  - cidr: 10.0.2.0/24
    zone: b
  - cidr: 10.0.3.0/24
    zone: c

eks_security_groups:
  - name: "{{ eks_cluster_name }}-control-plane-sg"
    description: "EKS Control Plane Security Group"
    rules:
      - group_name: "{{ eks_cluster_name }}-workers-sg"
        group_desc: "EKS Worker Security Group"
        ports: 443
        proto: tcp
    rules_egress:
      - group_name: "{{ eks_cluster_name }}-workers-sg"
        group_desc: "EKS Worker Security Group"
        from_port: 1025
        to_port: 65535
        proto: tcp
  - name: "{{ eks_cluster_name }}-workers-sg"
    description: "EKS Worker Security Group"
    rules:
      - group_name: "{{ eks_cluster_name }}-workers-sg"
        proto: tcp
        from_port: 1
        to_port: 65535
      - group_name: "{{ eks_cluster_name }}-control-plane-sg"
        ports: 10250
        proto: tcp
      - ports: 22
        proto: tcp
        cidr_ip: 0.0.0.0/0
      - from_port: 1
        to_port: 65535
        cidr_ip:
          - "{{ eks_subnets[0].cidr }}"
          - "{{ eks_subnets[1].cidr }}"
          - "{{ eks_subnets[2].cidr }}"
    tags:
      KubernetesCluster: "{{ eks_cluster_name }}"
